### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by mrn3** [ZenitechSoftware/lambda-node#3]
I have tried to implement this per your instructions, but getting:

START RequestId: 91186236-28a1-11e8-aa64-574f96b6f84f Version: $LATEST
Syntax error in module 'index': SyntaxError
(function (exports, require, module, __filename, __dirname) { module.exports.handler = async (event, context) => {
                                                                                             ^
SyntaxError: Unexpected token (

It seems it doesn't recognize async still.  Could you possibly make a video of you getting this running, or somehow explain the steps better?

**Comment by mrn3** [comment]
actually, I think I figured it out - it wasn't clear in your description that it should look like this:

<img width="1282" alt="screen shot 2018-03-15 at 4 58 36 pm" src="https://user-images.githubusercontent.com/3468214/37495298-2d8a3520-2872-11e8-9ecc-30f2796dcf75.png">

**Comment by ezhis** [comment]
@mrn3  Thanks for your feedback,  we will improve the docs

**Comment by mykolasmolis** [comment]
The screenshot was added to README.md 
Should be more clear now :)

**Comment by mrn3** [comment]
Great thx!
