### ISSUE TITLE
Not working - cannot execute binary file

### ISSUE THREAD

**Issue by anilsdas** [ZenitechSoftware/lambda-node#4]
Followed your install instructions, but getting below error always

....node_modules/lambda-node-runtime/src/../.node/bin/node: cannot execute binary file

bin/node file is there in folder. Tried in lambda server also, but getting error.

**Comment by anilsdas** [comment]
When running from lambda, below is the error

{"errorMessage":"Exit code 1","errorType":"Error","stackTrace":["CloseError (/var/task/node_modules/lambda-node-runtime/src/lambdaHandler.js:7:5)","buildCloseError (/var/task/node_modules/lambda-node-runtime/src/lambdaHandler.js:42:10)","ChildProcess.nodeChildProcess.on (/var/task/node_modules/lambda-node-runtime/src/lambdaHandler.js:46:45)","emitTwo (events.js:106:13)","ChildProcess.emit (events.js:191:7)","maybeClose (internal/child_process.js:886:16)","Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)"]}

**Comment by ezhis** [comment]
@anilsdas Can you share a source code of your setup?

**Comment by anilsdas** [comment]
@ezhis  i think the problem is when we use context.done instead of callback. Sample code below


handler.js

module.exports.hello = (event, context, callback) => {
  const response = { statusCode: 200, body: JSON.stringify({
      message: process.versions,
      input: event
    }) };

  context.done(null, response);
};



YML

service: versiontest
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    LAMBDA_NODE_HANDLER: handler.hello
plugins:
  - serverless-offline
functions:
  hello:
    handler: node_modules/lambda-node-runtime/index.handler
    events:
      - http:
          path: users/create
          method: get

**Comment by mykolasmolis** [comment]
Here is what AWS Lambda documentation says about `context.done` function:

> The callback is supported only in the Node.js runtimes v6.10 and v4.3. If you are using runtime v0.10.42, you need to use the context methods (done, succeed, and fail) to properly terminate the Lambda function. For information, see Using the Earlier Node.js Runtime v0.10.42.

Looks like you need to update your code to NOT use deprecated `context.done` function and use `callback` instead.

**Comment by anilsdas** [comment]
@Mykolas-Zenitech yes, i have updated to callback now. But the problem is that I am not able to access other functions in context also. eg. context.getRemainingTimeInMillis();

**Comment by mykolasmolis** [comment]
Currently AWS Lambda context object has only one function `getRemainingTimeInMillis`. It is not supported by `lambda-node-runtime`. However, since you need it - we are going to add it very soon (in a few days). I will let you know when it is done.

**Comment by mykolasmolis** [comment]
Raised issue #5

**Comment by mykolasmolis** [comment]
#5 is closed. getRemainingTimeInMillis function should be supported in starting version 0.0.22.

Can you please verify that it works for you?

**Comment by anilsdas** [comment]
@Mykolas-Zenitech  This is working now.. Thanks a lot for the update
